### PR TITLE
Surface MemphisSchemaError

### PR DESCRIPTION
**Pull request by rnowling-memphis**
Fixes issue #161 .  Specific changes include:

* Raise MemphisSchemaError instead of MemphisError when a schema violation occurs
* Outdent sending notification so that notification logic is independent of sending to dead-letter queue
* Make exceptions / error types raised by validation methods consistent

### CODE REVIEW

**Comment by rnowling-memphis** [comment]
@idanasulinmemphis do you have thoughts on this API change?

**Comment by idanasulinmemphis** [comment]
@rnowling-memphis no actually just having a lot of stuff these days, sorry for not updating.
I'll reach to it by the end of the week I believe

**Comment by rnowling-memphis** [comment]
Thanks, @idanasulinmemphis .  I believe this PR mixes up two things: surfacing the MemphisSchemaError and decoupling the notification from sending to the dead-letter queue.  I can undo the notification logic change if that would cause problems.  Surfacing the MemphisSchemaError instead of a more generic MemphisException is the important part.

**Review by idanasulinmemphis — APPROVED** [review]
Thanks @rnowling-memphis

**Pull request merged**
