### PR TITLE
avro validation

### PR DESCRIPTION
**Pull request by Big-Vi**
Related to https://github.com/memphisdev/memphis/pull/1107

I've used `https://github.com/fastavro/fastavro`  instead of `https://github.com/apache/avro` because of it's performance.

### CODE REVIEW

**Comment by idanasulinmemphis** [comment]
Looks great @Big-Vi, will be merged once we will merge the broker PR

**Review by idanasulinmemphis — APPROVED** [review]
@Big-Vi big thank you for this amazing contribution, approved.
Before merging just please resolve the lint issues

**Comment by Big-Vi** [comment]
> @Big-Vi big thank you for this amazing contribution, approved. Before merging just please resolve the lint issues

Resolved. Thanks.

**Review by rnowling-memphis — APPROVED** [review]

**Comment by rnowling-memphis** [comment]
@Big-Vi Fantastic work!  I merged your changes.

**Pull request merged**
